module.exports = {
  title: "C Y Stark",
  titleAlt: "Cam Yuji Stark - Web Developer",
  description: "Web Developer from Melbourne Australia",
  url: "https://cystark.com.au/",
  copyright: "© Designed and Developed by CYStark 2019",
  siteURL: "https://cystark.com.au/",
  siteLanguage: "en",
  logo: "src/images/logo.png",
  banner: "src/images/banner.jpg",
  favicon: "src/images/favicon.jpg",
  shortName: "CYStark",
  author: "CYStark",
  twitter: "@camyujistark",
  github: "@cystark",
  email: "cam@cystark.com.au",
  instagram: "cam.yuji.stark",
  linkedin: "cameron-stark-b0469721",
  pathPrefix: "/",
}
